name: datakit
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - typer
  - loguru
  - tqdm
  - black
  - flake8
  - isort
  - pandas
  - numpy 
  - tifffile
  - scikit-learn
  - matplotlib
  - ipython
  - jupyterlab
  - notebook
  - pytables # for pandas.HDFStore .hdf5 support
  - pip:
    - bokeh
    - python-dotenv
    - mkdocs
    - -e .